import React from 'react'
import style from './style.module.css'

function About() {
  return (
    <div className={style.content}>
      <h1>About VN Archive</h1>
      <p>This web application was made by Andrii Bialkovskyi (maphy9) as a side project to show off my skills in developing full stack applications.</p>
      <p>The main technologies used to develop this website are: ReactJS, Django, Postgresql.</p>
      <p>The content here is generated by AI or copy-pasted from the respective wikipedia articles. The images were taken from open sources on the realms of Internet.</p>
    </div>
  )
}

export default About