# Generated by Django 5.1.6 on 2025-02-11 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visualnovel',
            name='studio',
        ),
        migrations.AlterField(
            model_name='visualnovel',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='visual_novels', to='api.genre'),
        ),
    ]
