# Generated by Django 5.1.6 on 2025-02-17 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_paragraph_side_window'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualnovel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='visual_novel_images/'),
        ),
    ]
