# Generated by Django 5.1.6 on 2025-02-18 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_visualnovel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualnovel',
            name='description',
            field=models.TextField(default='Empty'),
            preserve_default=False,
        ),
    ]
