# Generated by Django 5.1.6 on 2025-02-19 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_discussion_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussion',
            old_name='text',
            new_name='description',
        ),
    ]
