# Generated by Django 5.1.6 on 2025-02-19 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_reply_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='discussions_images/'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.reply'),
        ),
    ]
